# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 61. Find the nearest value from a given value in an array (★★☆)

In [1]:
import numpy as np
x = np.random.uniform(3, 7, 16)
v = 7
n = x.flat[np.abs(x - v).argmin()]
print(n)

6.930569579662066


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [2]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        objct = np.asarray(array).view(cls)
        objct.name = name
        return objct
    def __array_finalize__(self, objct):
        if objct is None: return
        self.info = getattr(objct, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [4]:
X = np.ones(10)
Y = np.random.randint(0,len(Z),20)
Z += np.bincount(Y, minlength=len(Z))
print(Z)

[ 3  2  3  3  7  9  9  8 12  9]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [5]:
X = [1,2,3,4,5,6]
Y = [1,3,9,3,4,1]
Z = np.bincount(Y,X)
print(Z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [7]:
w,h = 13,13
X = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
Y = X[...,0]*169*169 + X[...,1]*169 +X[...,2]
n = len(np.unique(Y))
print(np.unique(X))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [6]:
M = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes 
sum = M.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
sum = M.reshape(M.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[50 60 49 52]
 [43 73 58 56]
 [54 69 55 54]]
[[50 60 49 52]
 [43 73 58 56]
 [54 69 55 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [8]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.59890957 0.56016859 0.51088324 0.50698438 0.51190401 0.49399893
 0.52864096 0.50842855 0.5599687  0.44079789]


#### 69. How to get the diagonal of a dot product? (★★★)

In [9]:
M= np.random.uniform(0,1,(5,5))
N = np.random.uniform(0,1,(5,5))

np.einsum("ij,ji->i", M, N)

array([1.35309453, 1.15045445, 1.30023288, 0.56452587, 1.43296035])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [12]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [13]:
M = np.ones((5,5,3))
N = 2*np.ones((5,5))
print(M * N[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [14]:
M = np.arange(25).reshape(5,5)
M[[0,1]] = M[[1,0]]
print(M)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [15]:
faces = np.random.randint(0,100,(10,3))
G = np.roll(faces.repeat(2,axis=1),-1,axis=1)
G = G.reshape(len(G)*3,2)
G = np.sort(G,axis=1)
Q = G.view( dtype=[('p0',G.dtype),('p1',G.dtype)] )
Q = np.unique(Q)
print(Q)

[( 1, 25) ( 1, 71) ( 9, 40) ( 9, 76) (13, 14) (13, 26) (14, 26) (14, 45)
 (14, 54) (14, 64) (14, 94) (20, 36) (20, 67) (22, 32) (22, 39) (25, 50)
 (25, 57) (25, 71) (32, 39) (36, 67) (40, 76) (40, 94) (40, 97) (45, 94)
 (50, 57) (54, 64) (60, 60) (60, 63) (94, 97)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [17]:
M = np.bincount([1,1,2,3,4,4,6])
N = np.repeat(np.arange(len(M)), M)
print(N)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [18]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [19]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [20]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.02597755,  0.02096481,  0.66214773, -0.42966578,  0.03888321,
        0.21227557, -0.41002973,  0.50129894, -0.70169451, -0.02046027,
       -0.21052088,  0.80638633, -0.96147792, -0.78046382, -0.34271476,
       -0.69851751,  0.05256926,  0.69383511, -0.26208247, -0.66988857,
        0.27906135, -0.90659362,  0.94061684,  0.10600238, -0.83769731,
        0.29956821, -0.33267765, -0.46258542,  0.56115683, -0.8645036 ,
        0.99019622,  0.68595072,  0.78614012, -0.88413124,  0.11269953,
       -0.16261525, -0.65518281,  0.09850113,  0.96342351, -0.5184997 ,
       -0.16984871, -0.35334021,  0.60652775,  0.77067204, -0.85754117,
        0.73712572,  0.60802933,  0.70149145,  0.12389732, -0.8133848 ,
       -0.45996665,  0.8319369 , -0.19439344,  0.5128267 ,  0.92959998,
        0.92178258,  0.87665527, -0.66532456,  0.6931626 ,  0.01839441,
       -0.39557693,  0.46489109,  0.78642793, -0.1938167 ,  0.46098645,
        0.33038915, -0.83047739, -0.83019416,  0.89140978,  0.59

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [21]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.47076765  9.27669035  3.13975837  9.65525716  2.49875329  7.02179348
 16.21567999  3.087863   17.20968244  2.20324484]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [22]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.76554938  1.13250348 11.04627698  7.09677248 13.05882997  9.61837844
   0.30482104  5.0678459   1.18009906 10.69217489]
 [ 7.43870699 12.04979677  2.75464643  6.0236811   3.71781147  3.12754405
   2.17024276  0.51299564  8.04944339  4.84637464]
 [ 1.56544822  2.71819002  7.84914346  3.35058693  9.62538173  5.63314402
   0.55142646  4.66205654  2.22900152  8.09374303]
 [ 2.50465992  1.55295383  8.87853118  4.47729249 10.72066898  6.86002571
   0.39933867  4.71097068  1.1404256   8.95120884]
 [ 8.34463585 15.69401132  4.77953147  9.06616294  3.63152587  8.4231956
   3.70325234  5.50809166 15.42352903  2.79452923]
 [13.41954395  5.86432893  4.945975   12.81870783  8.15758093 11.12517924
  12.5481005  17.53224479  3.85737775  2.35837741]
 [ 6.31468525  2.19327499 10.50901682  8.28690262 12.71514369 10.23685447
   2.01079717  6.87145615  0.81467471  9.7782153 ]
 [ 3.85255282  8.94130485  3.20542494  2.761982    4.55235284  0.63054067
   0.29547154  3.38205049  7.25713636  4.49572214]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [27]:
A = np.arange(1,15,dtype=np.uint32)
B = stride_tricks.as_strided(A,(11,4),(4,4))
print(B)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [28]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [29]:
A = np.random.randint(0,10,50)
print(np.bincount(A).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [30]:
A = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (A.shape[0]-3)
j = 1 + (A.shape[1]-3)
C = stride_tricks.as_strided(A, shape=(i, j, n, n), strides=A.strides + A.strides)
print(C)

[[[[1 0 3]
   [2 0 3]
   [1 2 1]]

  [[0 3 4]
   [0 3 3]
   [2 1 3]]

  [[3 4 1]
   [3 3 3]
   [1 3 4]]

  [[4 1 1]
   [3 3 2]
   [3 4 4]]

  [[1 1 1]
   [3 2 4]
   [4 4 4]]

  [[1 1 2]
   [2 4 4]
   [4 4 1]]

  [[1 2 4]
   [4 4 0]
   [4 1 4]]

  [[2 4 4]
   [4 0 1]
   [1 4 1]]]


 [[[2 0 3]
   [1 2 1]
   [3 0 0]]

  [[0 3 3]
   [2 1 3]
   [0 0 3]]

  [[3 3 3]
   [1 3 4]
   [0 3 2]]

  [[3 3 2]
   [3 4 4]
   [3 2 1]]

  [[3 2 4]
   [4 4 4]
   [2 1 2]]

  [[2 4 4]
   [4 4 1]
   [1 2 2]]

  [[4 4 0]
   [4 1 4]
   [2 2 3]]

  [[4 0 1]
   [1 4 1]
   [2 3 0]]]


 [[[1 2 1]
   [3 0 0]
   [3 1 3]]

  [[2 1 3]
   [0 0 3]
   [1 3 4]]

  [[1 3 4]
   [0 3 2]
   [3 4 3]]

  [[3 4 4]
   [3 2 1]
   [4 3 4]]

  [[4 4 4]
   [2 1 2]
   [3 4 3]]

  [[4 4 1]
   [1 2 2]
   [4 3 4]]

  [[4 1 4]
   [2 2 3]
   [3 4 4]]

  [[1 4 1]
   [2 3 0]
   [4 4 0]]]


 [[[3 0 0]
   [3 1 3]
   [3 1 4]]

  [[0 0 3]
   [1 3 4]
   [1 4 1]]

  [[0 3 2]
   [3 4 3]
   [4 1 2]]

  [[3 2 1]
   [4 3 4]
   [1 2 4]]

  [[2 1 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [31]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 18  3 13 13]
 [18  1 11 12  1]
 [ 3 11  6 42 11]
 [13 12 42  8  6]
 [13  1 11  6  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)